In [64]:
import re
import numpy as np
a = open('txt.ipynb', 'r')

v = []
x =['']
for f in a:
    b = re.split('[^a-z]', f.lower())
    f = [x for x in b if x]
    v.append(f)                     

d = { item for elem in v for item in elem}
g = [ i for i in d if i]
    
a = np.array([10])    
         
for m in v:
    for j in g:
        if j in m:
            a = np.append(a, 1)
        else:
            a = np.append(a, 0)
            
a = np.delete(a, 0)
b = a.reshape(22, 254)
print(b)
b.shape

print(b[: , 1])

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [65]:
from scipy.spatial import distance

i = 0
for i in range(len(v)):
    print(distance.cosine(b[0], b[i]))
    i += 1
    


0.0
0.9402385695332803
0.8619868881315291
0.8885443574849294
0.8055388829343507
0.9351796276447836
0.7547442642060137
0.9154845745271484
0.9069515789601529
0.8833576312960392
0.8703592552895671
0.8703592552895671
0.8773721321030068
0.8703592552895671
0.8619868881315291
0.9402385695332803
0.85361498905772
0.9503708333014534
0.9442721787424647
0.9402385695332803
0.8427572744917122
0.8250364469440588
